SELECT * FROM Suppliers;
SELECT * FROM Departments;
SELECT * FROM Customers;
SELECT * FROM Items;
SELECT * FROM Orders;
SELECT * FROM Feedbacks;
SELECT * FROM sell;
SELECT * FROM OrderItems;
SELECT * FROM OrderDetails;
